package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Averiasterminales generated by hbm2java
 */
@Entity
@Table(name = "averiasterminales", catalog = "telefonia")
public class Averiasterminales implements java.io.Serializable {

	private Integer idaveriasterminal;
	private Operadores operadores;
	private Terminales terminalesByImeiantiguo;
	private Terminales terminalesByImeinuevo;
	private Date fechaaveria;
	private Date fechaentrega;
	private String icc;
	private Boolean enviadoreparar;
	private String observaciones;

	public Averiasterminales() {
	}

	public Averiasterminales(Terminales terminalesByImeiantiguo, Terminales terminalesByImeinuevo, String icc) {
		this.terminalesByImeiantiguo = terminalesByImeiantiguo;
		this.terminalesByImeinuevo = terminalesByImeinuevo;
		this.icc = icc;
	}

	public Averiasterminales(Operadores operadores, Terminales terminalesByImeiantiguo,
			Terminales terminalesByImeinuevo, Date fechaaveria, Date fechaentrega, String icc, Boolean enviadoreparar,
			String observaciones) {
		this.operadores = operadores;
		this.terminalesByImeiantiguo = terminalesByImeiantiguo;
		this.terminalesByImeinuevo = terminalesByImeinuevo;
		this.fechaaveria = fechaaveria;
		this.fechaentrega = fechaentrega;
		this.icc = icc;
		this.enviadoreparar = enviadoreparar;
		this.observaciones = observaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idaveriasterminal", unique = true, nullable = false)
	public Integer getIdaveriasterminal() {
		return this.idaveriasterminal;
	}

	public void setIdaveriasterminal(Integer idaveriasterminal) {
		this.idaveriasterminal = idaveriasterminal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idoperador")
	public Operadores getOperadores() {
		return this.operadores;
	}

	public void setOperadores(Operadores operadores) {
		this.operadores = operadores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "imeiantiguo", nullable = false)
	public Terminales getTerminalesByImeiantiguo() {
		return this.terminalesByImeiantiguo;
	}

	public void setTerminalesByImeiantiguo(Terminales terminalesByImeiantiguo) {
		this.terminalesByImeiantiguo = terminalesByImeiantiguo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "imeinuevo", nullable = false)
	public Terminales getTerminalesByImeinuevo() {
		return this.terminalesByImeinuevo;
	}

	public void setTerminalesByImeinuevo(Terminales terminalesByImeinuevo) {
		this.terminalesByImeinuevo = terminalesByImeinuevo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaaveria", length = 10)
	public Date getFechaaveria() {
		return this.fechaaveria;
	}

	public void setFechaaveria(Date fechaaveria) {
		this.fechaaveria = fechaaveria;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaentrega", length = 10)
	public Date getFechaentrega() {
		return this.fechaentrega;
	}

	public void setFechaentrega(Date fechaentrega) {
		this.fechaentrega = fechaentrega;
	}

	@Column(name = "icc", nullable = false, length = 40)
	public String getIcc() {
		return this.icc;
	}

	public void setIcc(String icc) {
		this.icc = icc;
	}

	@Column(name = "enviadoreparar")
	public Boolean getEnviadoreparar() {
		return this.enviadoreparar;
	}

	public void setEnviadoreparar(Boolean enviadoreparar) {
		this.enviadoreparar = enviadoreparar;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
