package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Averiassim generated by hbm2java
 */
@Entity
@Table(name = "averiassim", catalog = "telefonia")
public class Averiassim implements java.io.Serializable {

	private Integer idaveriassim;
	private Operadores operadores;
	private Tarjetas tarjetasByTarjetaantigua;
	private Tarjetas tarjetasByTarjetanueva;
	private Date fechaaveriasim;
	private Date fechaentregasim;
	private String observaciones;

	public Averiassim() {
	}

	public Averiassim(Tarjetas tarjetasByTarjetaantigua, Tarjetas tarjetasByTarjetanueva) {
		this.tarjetasByTarjetaantigua = tarjetasByTarjetaantigua;
		this.tarjetasByTarjetanueva = tarjetasByTarjetanueva;
	}

	public Averiassim(Operadores operadores, Tarjetas tarjetasByTarjetaantigua, Tarjetas tarjetasByTarjetanueva,
			Date fechaaveriasim, Date fechaentregasim, String observaciones) {
		this.operadores = operadores;
		this.tarjetasByTarjetaantigua = tarjetasByTarjetaantigua;
		this.tarjetasByTarjetanueva = tarjetasByTarjetanueva;
		this.fechaaveriasim = fechaaveriasim;
		this.fechaentregasim = fechaentregasim;
		this.observaciones = observaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idaveriassim", unique = true, nullable = false)
	public Integer getIdaveriassim() {
		return this.idaveriassim;
	}

	public void setIdaveriassim(Integer idaveriassim) {
		this.idaveriassim = idaveriassim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idoperador")
	public Operadores getOperadores() {
		return this.operadores;
	}

	public void setOperadores(Operadores operadores) {
		this.operadores = operadores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tarjetaantigua", nullable = false)
	public Tarjetas getTarjetasByTarjetaantigua() {
		return this.tarjetasByTarjetaantigua;
	}

	public void setTarjetasByTarjetaantigua(Tarjetas tarjetasByTarjetaantigua) {
		this.tarjetasByTarjetaantigua = tarjetasByTarjetaantigua;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tarjetanueva", nullable = false)
	public Tarjetas getTarjetasByTarjetanueva() {
		return this.tarjetasByTarjetanueva;
	}

	public void setTarjetasByTarjetanueva(Tarjetas tarjetasByTarjetanueva) {
		this.tarjetasByTarjetanueva = tarjetasByTarjetanueva;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaaveriasim", length = 10)
	public Date getFechaaveriasim() {
		return this.fechaaveriasim;
	}

	public void setFechaaveriasim(Date fechaaveriasim) {
		this.fechaaveriasim = fechaaveriasim;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaentregasim", length = 10)
	public Date getFechaentregasim() {
		return this.fechaentregasim;
	}

	public void setFechaentregasim(Date fechaentregasim) {
		this.fechaentregasim = fechaentregasim;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
