package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DepartamentosAyto generated by hbm2java
 */
@Entity
@Table(name = "departamentosAyto", catalog = "telefonia")
public class DepartamentosAyto implements java.io.Serializable {

	private Integer idDepAyto;
	private String nomDepartamento;
	private Set empresasAytos = new HashSet(0);

	public DepartamentosAyto() {
	}

	public DepartamentosAyto(String nomDepartamento) {
		this.nomDepartamento = nomDepartamento;
	}

	public DepartamentosAyto(String nomDepartamento, Set empresasAytos) {
		this.nomDepartamento = nomDepartamento;
		this.empresasAytos = empresasAytos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDepAyto", unique = true, nullable = false)
	public Integer getIdDepAyto() {
		return this.idDepAyto;
	}

	public void setIdDepAyto(Integer idDepAyto) {
		this.idDepAyto = idDepAyto;
	}

	@Column(name = "nomDepartamento", nullable = false, length = 70)
	public String getNomDepartamento() {
		return this.nomDepartamento;
	}

	public void setNomDepartamento(String nomDepartamento) {
		this.nomDepartamento = nomDepartamento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamentosAyto")
	public Set getEmpresasAytos() {
		return this.empresasAytos;
	}

	public void setEmpresasAytos(Set empresasAytos) {
		this.empresasAytos = empresasAytos;
	}

}
