package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmpresasAyto generated by hbm2java
 */
@Entity
@Table(name = "empresasAyto", catalog = "telefonia")
public class EmpresasAyto implements java.io.Serializable {

	private Integer idEmpAyto;
	private DepartamentosAyto departamentosAyto;
	private String nomEmpresa;
	private Set usuarioses = new HashSet(0);

	public EmpresasAyto() {
	}

	public EmpresasAyto(String nomEmpresa) {
		this.nomEmpresa = nomEmpresa;
	}

	public EmpresasAyto(DepartamentosAyto departamentosAyto, String nomEmpresa, Set usuarioses) {
		this.departamentosAyto = departamentosAyto;
		this.nomEmpresa = nomEmpresa;
		this.usuarioses = usuarioses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEmpAyto", unique = true, nullable = false)
	public Integer getIdEmpAyto() {
		return this.idEmpAyto;
	}

	public void setIdEmpAyto(Integer idEmpAyto) {
		this.idEmpAyto = idEmpAyto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDepAyto")
	public DepartamentosAyto getDepartamentosAyto() {
		return this.departamentosAyto;
	}

	public void setDepartamentosAyto(DepartamentosAyto departamentosAyto) {
		this.departamentosAyto = departamentosAyto;
	}

	@Column(name = "nomEmpresa", nullable = false, length = 70)
	public String getNomEmpresa() {
		return this.nomEmpresa;
	}

	public void setNomEmpresa(String nomEmpresa) {
		this.nomEmpresa = nomEmpresa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresasAyto")
	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}

}
