package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entregas generated by hbm2java
 */
@Entity
@Table(name = "entregas", catalog = "telefonia")
public class Entregas implements java.io.Serializable {

	private Integer identrega;
	private Operadores operadores;
	private Tarjetas tarjetas;
	private Terminales terminales;
	private Usuarios usuarios;
	private Date fechaentrega;
	private String firmarecepcion;
	private String observaciones;

	public Entregas() {
	}

	public Entregas(Date fechaentrega, String firmarecepcion) {
		this.fechaentrega = fechaentrega;
		this.firmarecepcion = firmarecepcion;
	}

	public Entregas(Operadores operadores, Tarjetas tarjetas, Terminales terminales, Usuarios usuarios,
			Date fechaentrega, String firmarecepcion, String observaciones) {
		this.operadores = operadores;
		this.tarjetas = tarjetas;
		this.terminales = terminales;
		this.usuarios = usuarios;
		this.fechaentrega = fechaentrega;
		this.firmarecepcion = firmarecepcion;
		this.observaciones = observaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "identrega", unique = true, nullable = false)
	public Integer getIdentrega() {
		return this.identrega;
	}

	public void setIdentrega(Integer identrega) {
		this.identrega = identrega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idoperador")
	public Operadores getOperadores() {
		return this.operadores;
	}

	public void setOperadores(Operadores operadores) {
		this.operadores = operadores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtarjeta")
	public Tarjetas getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(Tarjetas tarjetas) {
		this.tarjetas = tarjetas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idterminal")
	public Terminales getTerminales() {
		return this.terminales;
	}

	public void setTerminales(Terminales terminales) {
		this.terminales = terminales;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaentrega", nullable = false, length = 10)
	public Date getFechaentrega() {
		return this.fechaentrega;
	}

	public void setFechaentrega(Date fechaentrega) {
		this.fechaentrega = fechaentrega;
	}

	@Column(name = "firmarecepcion", nullable = false, length = 40)
	public String getFirmarecepcion() {
		return this.firmarecepcion;
	}

	public void setFirmarecepcion(String firmarecepcion) {
		this.firmarecepcion = firmarecepcion;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
