package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name = "estados", catalog = "telefonia")
public class Estados implements java.io.Serializable {

	private Integer idestado;
	private String estado;
	private Boolean activo;
	private Set histestadoses = new HashSet(0);
	private Set terminaleses = new HashSet(0);

	public Estados() {
	}

	public Estados(String estado, Boolean activo, Set histestadoses, Set terminaleses) {
		this.estado = estado;
		this.activo = activo;
		this.histestadoses = histestadoses;
		this.terminaleses = terminaleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idestado", unique = true, nullable = false)
	public Integer getIdestado() {
		return this.idestado;
	}

	public void setIdestado(Integer idestado) {
		this.idestado = idestado;
	}

	@Column(name = "estado", length = 70)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set getHistestadoses() {
		return this.histestadoses;
	}

	public void setHistestadoses(Set histestadoses) {
		this.histestadoses = histestadoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set getTerminaleses() {
		return this.terminaleses;
	}

	public void setTerminaleses(Set terminaleses) {
		this.terminaleses = terminaleses;
	}

}
