package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marcas generated by hbm2java
 */
@Entity
@Table(name = "marcas", catalog = "telefonia")
public class Marcas implements java.io.Serializable {

	private Integer idmarca;
	private String marca;
	private Boolean activo;
	private Set terminaleses = new HashSet(0);

	public Marcas() {
	}

	public Marcas(String marca) {
		this.marca = marca;
	}

	public Marcas(String marca, Boolean activo, Set terminaleses) {
		this.marca = marca;
		this.activo = activo;
		this.terminaleses = terminaleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmarca", unique = true, nullable = false)
	public Integer getIdmarca() {
		return this.idmarca;
	}

	public void setIdmarca(Integer idmarca) {
		this.idmarca = idmarca;
	}

	@Column(name = "marca", nullable = false, length = 70)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marcas")
	public Set getTerminaleses() {
		return this.terminaleses;
	}

	public void setTerminaleses(Set terminaleses) {
		this.terminaleses = terminaleses;
	}

}
