package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Numeros generated by hbm2java
 */
@Entity
@Table(name = "numeros", catalog = "telefonia", uniqueConstraints = { @UniqueConstraint(columnNames = "numcorto"),
		@UniqueConstraint(columnNames = "numlargo") })
public class Numeros implements java.io.Serializable {

	private Integer idnumero;
	private String numcorto;
	private String numlargo;
	private String observaciones;
	private Boolean activo;
	private Set tarjetases = new HashSet(0);

	public Numeros() {
	}

	public Numeros(String numcorto, String numlargo) {
		this.numcorto = numcorto;
		this.numlargo = numlargo;
	}

	public Numeros(String numcorto, String numlargo, String observaciones, Boolean activo, Set tarjetases) {
		this.numcorto = numcorto;
		this.numlargo = numlargo;
		this.observaciones = observaciones;
		this.activo = activo;
		this.tarjetases = tarjetases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idnumero", unique = true, nullable = false)
	public Integer getIdnumero() {
		return this.idnumero;
	}

	public void setIdnumero(Integer idnumero) {
		this.idnumero = idnumero;
	}

	@Column(name = "numcorto", unique = true, nullable = false, length = 70)
	public String getNumcorto() {
		return this.numcorto;
	}

	public void setNumcorto(String numcorto) {
		this.numcorto = numcorto;
	}

	@Column(name = "numlargo", unique = true, nullable = false, length = 70)
	public String getNumlargo() {
		return this.numlargo;
	}

	public void setNumlargo(String numlargo) {
		this.numlargo = numlargo;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "numeros")
	public Set getTarjetases() {
		return this.tarjetases;
	}

	public void setTarjetases(Set tarjetases) {
		this.tarjetases = tarjetases;
	}

}
