package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operadores generated by hbm2java
 */
@Entity
@Table(name = "operadores", catalog = "telefonia")
public class Operadores implements java.io.Serializable {

	private Integer idoperador;
	private String usuariooperador;
	private Set entregases = new HashSet(0);
	private Set averiasterminaleses = new HashSet(0);
	private Set averiassims = new HashSet(0);

	public Operadores() {
	}

	public Operadores(String usuariooperador) {
		this.usuariooperador = usuariooperador;
	}

	public Operadores(String usuariooperador, Set entregases, Set averiasterminaleses, Set averiassims) {
		this.usuariooperador = usuariooperador;
		this.entregases = entregases;
		this.averiasterminaleses = averiasterminaleses;
		this.averiassims = averiassims;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idoperador", unique = true, nullable = false)
	public Integer getIdoperador() {
		return this.idoperador;
	}

	public void setIdoperador(Integer idoperador) {
		this.idoperador = idoperador;
	}

	@Column(name = "usuariooperador", nullable = false, length = 70)
	public String getUsuariooperador() {
		return this.usuariooperador;
	}

	public void setUsuariooperador(String usuariooperador) {
		this.usuariooperador = usuariooperador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadores")
	public Set getEntregases() {
		return this.entregases;
	}

	public void setEntregases(Set entregases) {
		this.entregases = entregases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadores")
	public Set getAveriasterminaleses() {
		return this.averiasterminaleses;
	}

	public void setAveriasterminaleses(Set averiasterminaleses) {
		this.averiasterminaleses = averiasterminaleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadores")
	public Set getAveriassims() {
		return this.averiassims;
	}

	public void setAveriassims(Set averiassims) {
		this.averiassims = averiassims;
	}

}
