package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tarjetas generated by hbm2java
 */
@Entity
@Table(name = "tarjetas", catalog = "telefonia", uniqueConstraints = @UniqueConstraint(columnNames = "icc"))
public class Tarjetas implements java.io.Serializable {

	private Integer idtarjeta;
	private Numeros numeros;
	private Tipostarifas tipostarifas;
	private Tipostarjetas tipostarjetas;
	private int pin;
	private int puk;
	private String icc;
	private String tipo;
	private Boolean disponible;
	private String historialaveria;
	private String observaciones;
	private Set entregases = new HashSet(0);
	private Set averiassimsForTarjetaantigua = new HashSet(0);
	private Set averiassimsForTarjetanueva = new HashSet(0);

	public Tarjetas() {
	}

	public Tarjetas(int pin, int puk, String icc, String tipo) {
		this.pin = pin;
		this.puk = puk;
		this.icc = icc;
		this.tipo = tipo;
	}

	public Tarjetas(Numeros numeros, Tipostarifas tipostarifas, Tipostarjetas tipostarjetas, int pin, int puk,
			String icc, String tipo, Boolean disponible, String historialaveria, String observaciones, Set entregases,
			Set averiassimsForTarjetaantigua, Set averiassimsForTarjetanueva) {
		this.numeros = numeros;
		this.tipostarifas = tipostarifas;
		this.tipostarjetas = tipostarjetas;
		this.pin = pin;
		this.puk = puk;
		this.icc = icc;
		this.tipo = tipo;
		this.disponible = disponible;
		this.historialaveria = historialaveria;
		this.observaciones = observaciones;
		this.entregases = entregases;
		this.averiassimsForTarjetaantigua = averiassimsForTarjetaantigua;
		this.averiassimsForTarjetanueva = averiassimsForTarjetanueva;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtarjeta", unique = true, nullable = false)
	public Integer getIdtarjeta() {
		return this.idtarjeta;
	}

	public void setIdtarjeta(Integer idtarjeta) {
		this.idtarjeta = idtarjeta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idnumero")
	public Numeros getNumeros() {
		return this.numeros;
	}

	public void setNumeros(Numeros numeros) {
		this.numeros = numeros;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipotarifa")
	public Tipostarifas getTipostarifas() {
		return this.tipostarifas;
	}

	public void setTipostarifas(Tipostarifas tipostarifas) {
		this.tipostarifas = tipostarifas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipotarjeta")
	public Tipostarjetas getTipostarjetas() {
		return this.tipostarjetas;
	}

	public void setTipostarjetas(Tipostarjetas tipostarjetas) {
		this.tipostarjetas = tipostarjetas;
	}

	@Column(name = "pin", nullable = false)
	public int getPin() {
		return this.pin;
	}

	public void setPin(int pin) {
		this.pin = pin;
	}

	@Column(name = "puk", nullable = false)
	public int getPuk() {
		return this.puk;
	}

	public void setPuk(int puk) {
		this.puk = puk;
	}

	@Column(name = "icc", unique = true, nullable = false, length = 40)
	public String getIcc() {
		return this.icc;
	}

	public void setIcc(String icc) {
		this.icc = icc;
	}

	@Column(name = "tipo", nullable = false, length = 70)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "disponible")
	public Boolean getDisponible() {
		return this.disponible;
	}

	public void setDisponible(Boolean disponible) {
		this.disponible = disponible;
	}

	@Column(name = "historialaveria", length = 250)
	public String getHistorialaveria() {
		return this.historialaveria;
	}

	public void setHistorialaveria(String historialaveria) {
		this.historialaveria = historialaveria;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjetas")
	public Set getEntregases() {
		return this.entregases;
	}

	public void setEntregases(Set entregases) {
		this.entregases = entregases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjetasByTarjetaantigua")
	public Set getAveriassimsForTarjetaantigua() {
		return this.averiassimsForTarjetaantigua;
	}

	public void setAveriassimsForTarjetaantigua(Set averiassimsForTarjetaantigua) {
		this.averiassimsForTarjetaantigua = averiassimsForTarjetaantigua;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjetasByTarjetanueva")
	public Set getAveriassimsForTarjetanueva() {
		return this.averiassimsForTarjetanueva;
	}

	public void setAveriassimsForTarjetanueva(Set averiassimsForTarjetanueva) {
		this.averiassimsForTarjetanueva = averiassimsForTarjetanueva;
	}

}
