package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tiposdispositivos generated by hbm2java
 */
@Entity
@Table(name = "tiposdispositivos", catalog = "telefonia")
public class Tiposdispositivos implements java.io.Serializable {

	private Integer idtipodispositivo;
	private String tipo;
	private Boolean activo;
	private Set terminaleses = new HashSet(0);

	public Tiposdispositivos() {
	}

	public Tiposdispositivos(String tipo) {
		this.tipo = tipo;
	}

	public Tiposdispositivos(String tipo, Boolean activo, Set terminaleses) {
		this.tipo = tipo;
		this.activo = activo;
		this.terminaleses = terminaleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipodispositivo", unique = true, nullable = false)
	public Integer getIdtipodispositivo() {
		return this.idtipodispositivo;
	}

	public void setIdtipodispositivo(Integer idtipodispositivo) {
		this.idtipodispositivo = idtipodispositivo;
	}

	@Column(name = "tipo", nullable = false, length = 70)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposdispositivos")
	public Set getTerminaleses() {
		return this.terminaleses;
	}

	public void setTerminaleses(Set terminaleses) {
		this.terminaleses = terminaleses;
	}

}
