package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipostarifas generated by hbm2java
 */
@Entity
@Table(name = "tipostarifas", catalog = "telefonia")
public class Tipostarifas implements java.io.Serializable {

	private Integer idtipotarifa;
	private String tipotarifa;
	private String observaciones;
	private Boolean activo;
	private Set tarjetases = new HashSet(0);

	public Tipostarifas() {
	}

	public Tipostarifas(String tipotarifa) {
		this.tipotarifa = tipotarifa;
	}

	public Tipostarifas(String tipotarifa, String observaciones, Boolean activo, Set tarjetases) {
		this.tipotarifa = tipotarifa;
		this.observaciones = observaciones;
		this.activo = activo;
		this.tarjetases = tarjetases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipotarifa", unique = true, nullable = false)
	public Integer getIdtipotarifa() {
		return this.idtipotarifa;
	}

	public void setIdtipotarifa(Integer idtipotarifa) {
		this.idtipotarifa = idtipotarifa;
	}

	@Column(name = "tipotarifa", nullable = false, length = 70)
	public String getTipotarifa() {
		return this.tipotarifa;
	}

	public void setTipotarifa(String tipotarifa) {
		this.tipotarifa = tipotarifa;
	}

	@Column(name = "observaciones", length = 250)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipostarifas")
	public Set getTarjetases() {
		return this.tarjetases;
	}

	public void setTarjetases(Set tarjetases) {
		this.tarjetases = tarjetases;
	}

}
