package muestra;
// Generated 25-ene-2018 9:22:35 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "telefonia", uniqueConstraints = @UniqueConstraint(columnNames = "dni"))
public class Usuarios implements java.io.Serializable {

	private Integer idUsuario;
	private EmpresasAyto empresasAyto;
	private String nombreusuario;
	private String nombre;
	private String primerApellido;
	private String segundoApellido;
	private String dni;
	private String correo;
	private Set entregases = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombreusuario, String nombre, String primerApellido, String dni, String correo) {
		this.nombreusuario = nombreusuario;
		this.nombre = nombre;
		this.primerApellido = primerApellido;
		this.dni = dni;
		this.correo = correo;
	}

	public Usuarios(EmpresasAyto empresasAyto, String nombreusuario, String nombre, String primerApellido,
			String segundoApellido, String dni, String correo, Set entregases) {
		this.empresasAyto = empresasAyto;
		this.nombreusuario = nombreusuario;
		this.nombre = nombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.dni = dni;
		this.correo = correo;
		this.entregases = entregases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUsuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEmpAyto")
	public EmpresasAyto getEmpresasAyto() {
		return this.empresasAyto;
	}

	public void setEmpresasAyto(EmpresasAyto empresasAyto) {
		this.empresasAyto = empresasAyto;
	}

	@Column(name = "nombreusuario", nullable = false, length = 70)
	public String getNombreusuario() {
		return this.nombreusuario;
	}

	public void setNombreusuario(String nombreusuario) {
		this.nombreusuario = nombreusuario;
	}

	@Column(name = "nombre", nullable = false, length = 70)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "primerApellido", nullable = false, length = 70)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundoApellido", length = 70)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "dni", unique = true, nullable = false, length = 70)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "correo", nullable = false, length = 70)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set getEntregases() {
		return this.entregases;
	}

	public void setEntregases(Set entregases) {
		this.entregases = entregases;
	}

}
